import type { DetailsStrings } from '../../webview/detailsProtocol';
import type { PanelStrings } from '../../webview/protocol';

/** 状態の呼び名（英語の原文） */
const STATUS_LABELS = {
  draft: 'Draft',
  running: 'Running',
  approval: 'Needs approval',
  question: 'Question',
  replied: 'Replied',
  review: 'Review',
  done: 'Done',
  failed: 'Failed',
  interrupted: 'Interrupted',
};

/** タスク画面のテストで使う文字列（翻訳前の英語） */
export const PANEL_STRINGS: PanelStrings = {
  send: 'Send',
  stop: 'Stop',
  runningTurn: 'Turn {0} running · {1}',
  elapsedSeconds: '{0}s',
  elapsedMinutes: '{0}m {1}s',
  allow: 'Allow',
  allowAlways: 'Always allow',
  alwaysScope: 'Always allow covers: {0}',
  deny: 'Deny…',
  denyConfirm: 'Deny',
  denyReason: 'Reason (optional)',
  approvalTitles: {
    command: 'Run this command?',
    edit: 'Edit this file?',
    web: 'Access the web?',
    other: 'Use {0}?',
    plan: 'Approve the plan and start?',
  },
  approvePlan: 'Approve and implement',
  openPlan: 'Open in editor',
  mcpServers: 'MCP servers',
  mcpNotRunning: 'Shown while Claude Code is running for this task',
  mcpNone: 'None',
  mcpStatus: {
    connected: 'Connected',
    failed: 'Failed',
    'needs-auth': 'Needs authentication',
    pending: 'Connecting',
    disabled: 'Disabled',
  },
  planMode: 'Plan only',
  planModeHint: 'Claude reads and plans, and asks before it edits',
  inputDetails: 'Input details (JSON)',
  answer: 'Answer',
  other: 'Other (write your own)',
  otherPlaceholder: 'Your answer',
  questionKeys: 'Press 1–{0} to choose, Enter to answer',
  questionTabKeys: 'Press 1–{0} to choose, ←/→ to switch questions',
  submitTab: 'Submit',
  next: 'Next',
  unanswered: 'Not answered',
  waiting: 'Waiting for your input',
  changesInTurn: 'Changes in turn {0}',
  files: 'files',
  openDiff: 'Open diff',
  revert: 'Revert',
  reverted: 'Reverted',
  unknownBefore: 'Changed by the shell (cannot revert)',
  model: 'Model',
  defaultModel: 'Default',
  defaultModelWith: 'Default ({0})',
  effort: 'Effort',
  effortLabels: {
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    xhigh: 'Extra high',
    max: 'Max',
  },
  previousModel: 'Previous turn: {0}',
  attachments: 'Attachments',
  remove: 'Remove',
  promptHint: 'Follow-up (Ctrl+Enter to send)',
  promptHintPresets: 'Follow-up (Ctrl+Enter to send · / for presets)',
  draftHint: 'Write the next instruction while Claude works (send it after the turn ends)',
  dropHint: 'Drop files to attach (hold Shift when dragging from the editor)',
  selection: 'Selection',
  diagnostics: 'Diagnostics',
  gitDiff: 'git diff',
  addFile: 'File',
  statusLabels: STATUS_LABELS,
  worktree: 'worktree',
  merge: 'Merge into {0}',
  merging: 'Merging…',
  toolCalls: '{0} tool calls',
  thinking: 'Thinking…',
  thought: 'Thought',
  compact: 'Compact the context',
  compacted: 'Context compacted ({0} → {1})',
  commandsHint: 'Claude Code commands and skills',
  moreCandidates: '{0} more: keep typing to filter',
  more: 'More actions',
  rename: 'Rename',
  contextPanel: 'What Claude will receive',
  contextEmpty: 'Type a prompt to preview what will be sent.',
  permissionMode: 'Permission mode',
  alwaysAllowedList: 'Always allowed in this task',
  directory: 'Directory',
  noAttachments: 'No attachments',
  attachmentCount: '{0} attached',
  turn: 'Turn {0}',
  rewind: 'Rewind',
  fork: 'Fork',
  rewindHere: 'Rewind to here',
  forkHere: 'Fork from here',
  approveAndDone: 'Approve and finish',
  approved: 'Approved',
  unapprove: 'Undo approval',
  markDone: 'Mark as done',
  revertAll: 'Revert all',
  contextUsage: 'Context',
};

/** 右サイドバーのテストで使う文字列（翻訳前の英語） */
export const DETAILS_STRINGS: DetailsStrings = {
  noTask: 'Open a task to see its changes here.',
  turn: 'Turn {0}',
  openDiff: 'Open diff',
  revert: 'Revert',
  reverted: 'Reverted',
  rewindHere: 'Rewind to here',
  forkHere: 'Fork from here',
  noChanges: 'No changes',
  none: 'None',
  statusLabels: STATUS_LABELS,
  changesTitle: 'Changes in this task',
  finish: 'Finish',
  allDiff: 'Whole diff',
  merge: 'Merge into {0}',
  discardWorktree: 'Discard worktree…',
  stepApproved: 'Changes approved ({0} turns · {1} files)',
  stepApprove: 'Approve the changes',
  stepReview: 'Review the whole diff',
  stepMerge: 'Bring the changes into {0}',
  endWithoutMerge: 'End without merging',
  endWithoutChanges: 'End without keeping anything',
  nothingToMerge: 'Nothing to merge',
  nothingToMergeHint:
    'No files have changed in this task yet. Once there are changes, approve them to merge from here.',
};
